/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.minigdx.gradle.plugin

import com.github.minigdx.gradle.plugin.internal.MiniGdxException
import com.github.minigdx.gradle.plugin.internal.Severity
import com.github.minigdx.gradle.plugin.internal.Solution
import com.github.minigdx.gradle.plugin.internal.createDir
import com.github.minigdx.gradle.plugin.internal.maybeCreateMiniGdxExtension
import com.github.minigdx.gradle.plugin.internal.minigdx
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.tasks.JavaExec
import org.gradle.jvm.tasks.Jar
import java.io.File
import java.net.URI

class MiniGdxJvmGradlePlugin : Plugin<Project> {

    override fun apply(project: Project) {
        project.maybeCreateMiniGdxExtension()

        project.apply { plugin("org.jetbrains.kotlin.jvm") }

        configureSourceSets(project)
        configureProjectRepository(project)

        project.afterEvaluate {
            configureMiniGdxDependencies(project, minigdx)
            configureTasks(project, minigdx)
        }
        // TODO:
        //   configure build chain to get java 11 and jpackage
        //   https://walczak.it/blog/distributing-javafx-desktop-applications-without-requiring-jvm-using-jlink-and-jpackage
    }

    private fun configureProjectRepository(project: Project) {
        project.repositories.mavenCentral()
        project.repositories.google()
        // Snapshot repository. Select only our snapshot dependencies
        project.repositories.maven {
            url = URI("https://s01.oss.sonatype.org/content/repositories/snapshots/")
        }.mavenContent {
            includeVersionByRegex("com.github.minigdx", "(.*)", "LATEST-SNAPSHOT")
            includeVersionByRegex("com.github.minigdx.(.*)", "(.*)", "LATEST-SNAPSHOT")
        }
        project.repositories.mavenLocal()
        // Will be deprecated soon... Required for dokka
        project.repositories.jcenter()
    }

    private fun configureSourceSets(project: Project) {
        project.createDir("src/main/kotlin")
        project.createDir("src/test/kotlin")
    }

    private fun configureMiniGdxDependencies(project: Project, minigdx: MiniGdxExtension) {
        project.afterEvaluate {
            project.dependencies.add(
                "implementation",
                "com.github.minigdx:minigdx-jvm:${minigdx.version.get()}"
            )
        }
    }

    private fun configureTasks(project: Project, minigdx: MiniGdxExtension) {
        project.apply { plugin("org.gradle.application") }

        project.tasks.register("runJvm", JavaExec::class.java) {
            checkMainClass(project, minigdx)
            group = "minigdx"
            description = "Run your game on the JVM."
            jvmArgs = listOf("-XstartOnFirstThread")
            workingDir = project.projectDir.resolve(File("../common/src/commonMain/resources"))
            mainClass.set(minigdx.jvm.mainClass)
            classpath = project.files(
                project.tasks.getByName("classes").outputs,
                project.configurations.getByName("runtimeClasspath")
            )
        }

        project.tasks.register("bundleJar", Jar::class.java) {
            checkMainClass(project, minigdx)
            group = "minigdx"
            description = "Create a bundle as a Fat "

            archiveFileName.set("${project.rootProject.name}-jvm.jar")
            manifest {
                attributes(mapOf("Main-Class" to (project.minigdx.jvm.mainClass.get())))
            }

            from(project.projectDir.resolve(File("../common/src/commonMain/resources")))
            from(project.tasks.named("classes"))
            val dependenciesJar = project.configurations.getByName("runtimeClasspath").files
            val flatClasses = dependenciesJar.filter { it.exists() }
                .map { deps ->
                    if (deps.isDirectory) {
                        project.fileTree(deps)
                    } else {
                        project.zipTree(deps)
                    }
                }
            from(flatClasses)
            destinationDirectory.set(project.buildDir.resolve("minigdx"))
            doLast {
                project.logger.lifecycle("[MINIGDX] The jar distribution of your game is available at: ${outputs.files.first()}")
            }
        }
    }

    private fun checkMainClass(project: Project, minigdx: MiniGdxExtension) {
        if (!minigdx.jvm.mainClass.isPresent) {
            throw MiniGdxException.create(
                severity = Severity.EASY,
                project = project,
                because = "The main class used to start the game is not configured.",
                description = "MiniGDX needs the name of the class that will start the game to configure how to run it.",
                solutions = listOf(
                    Solution(
                        description =
                            """Add the configuration of the main class in your gradle build script:
                            | minigdx {
                            |   jvm.mainClass.set("com.example.MainKt")
                            | 
                            | }
                        """.trimMargin()

                    )
                )
            )
        }
    }
}
