/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package minigdx.gradle.plugin

import minigdx.gradle.plugin.internal.MiniGdxPlatform
import minigdx.gradle.plugin.internal.checkCommonPlugin
import minigdx.gradle.plugin.internal.createDir
import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class MiniGdxJvmGradlePlugin : Plugin<Project> {

    override fun apply(project: Project) {
        project.checkCommonPlugin(MiniGdxPlatform.JVM)

        configureMiniGdxDependencies(project)
        configureSourceSets(project)
        // TODO:
        //   configure task to create a templated game
        //   configure task to run application
        //   configure task to bundle fat jar
        //   configure task to bundle app+jvm ?
        //   configure pipeline pour github ?
        //   configure build chain to get java 11 and jpackage
        //   https://walczak.it/blog/distributing-javafx-desktop-applications-without-requiring-jvm-using-jlink-and-jpackage
    }

    private fun configureSourceSets(project: Project) {
        project.createDir("src/jvmMain/kotlin")
        project.createDir("src/jvmTest/kotlin")
    }

    private fun configureMiniGdxDependencies(project: Project) {
        project.afterEvaluate {
            project.dependencies.add("jvmMainImplementation", "com.github.minigdx:minigdx-jvm:DEV-SNAPSHOT")
        }
    }
}
